services:
  mysql:
    image: mysql:8.0
    container_name: dynamicBrandsMysql
    environment:
      MYSQL_ROOT_PASSWORD: root123
      MYSQL_DATABASE: dynamicBrandsDB
    ports:
      - "3306:3306"
    volumes:
      - ./mysql:/docker-entrypoint-initdb.d
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-uroot", "-proot123"]
      interval: 5s
      timeout: 5s
      retries: 30

  postgres:
    image: postgis/postgis:15-3.4
    container_name: etheriaPostgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
    ports:
      - "5432:5432"
    volumes:
      - ./postgres:/docker-entrypoint-initdb.d
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 30

  etl:
    build: ./etl
    container_name: etheriaEtl
    depends_on:
      mysql:
        condition: service_healthy
      postgres:
        condition: service_healthy