USE dynamicBrandsDB;
DELIMITER $$
DROP PROCEDURE IF EXISTS spSeedFullData $$
CREATE PROCEDURE spSeedFullData()
BEGIN
    DECLARE usdCurrencyID BIGINT;
    DECLARE crcCurrencyID BIGINT;
    DECLARE mxnCurrencyID BIGINT;
    DECLARE copCurrencyID BIGINT;
    DECLARE penCurrencyID BIGINT;
    DECLARE gtqCurrencyID BIGINT;
    DECLARE costaRicaCountryID BIGINT;
    DECLARE mexicoCountryID BIGINT;
    DECLARE colombiaCountryID BIGINT;
    DECLARE peruCountryID BIGINT;
    DECLARE guatemalaCountryID BIGINT;
    DECLARE adminPersonID BIGINT;
    DECLARE managerPersonID BIGINT;
    DECLARE cust1PersonID BIGINT;
    DECLARE cust2PersonID BIGINT;
    DECLARE cust3PersonID BIGINT;
    DECLARE cust4PersonID BIGINT;
    DECLARE cust5PersonID BIGINT;
    DECLARE site1ID BIGINT;
    DECLARE site2ID BIGINT;
    DECLARE site3ID BIGINT;
    DECLARE site4ID BIGINT;
    DECLARE site5ID BIGINT;
    DECLARE site6ID BIGINT;
    DECLARE site7ID BIGINT;
    DECLARE site8ID BIGINT;
    DECLARE site9ID BIGINT;
    DECLARE prodID BIGINT;
    DECLARE order1ID BIGINT;
    DECLARE order2ID BIGINT;
    DECLARE order3ID BIGINT;
    DECLARE order4ID BIGINT;
    DECLARE order5ID BIGINT;
    DECLARE EXIT HANDLER FOR SQLEXCEPTION
    BEGIN
        ROLLBACK;
        CALL spLogEtlStep('spSeedFullData', 'MANUAL', 'dynamicBrandsDB', 'ERROR', 0, 0, 'Error durante el seed de datos');
    END;
    START TRANSACTION;
    CALL spSeedBaseCatalogs();
    CALL spInsertCurrency('USD', 'US Dollar', '$');
    CALL spInsertCurrency('CRC', 'Costa Rican Colon', '₡');
    CALL spInsertCurrency('MXN', 'Mexican Peso', '$');
    CALL spInsertCurrency('COP', 'Colombian Peso', '$');
    CALL spInsertCurrency('PEN', 'Peruvian Sol', 'S/');
    CALL spInsertCurrency('GTQ', 'Guatemalan Quetzal', 'Q');
    SELECT currencyID INTO usdCurrencyID FROM currency WHERE currencyCode = 'USD' LIMIT 1;
    SELECT currencyID INTO crcCurrencyID FROM currency WHERE currencyCode = 'CRC' LIMIT 1;
    SELECT currencyID INTO mxnCurrencyID FROM currency WHERE currencyCode = 'MXN' LIMIT 1;
    SELECT currencyID INTO copCurrencyID FROM currency WHERE currencyCode = 'COP' LIMIT 1;
    SELECT currencyID INTO penCurrencyID FROM currency WHERE currencyCode = 'PEN' LIMIT 1;
    SELECT currencyID INTO gtqCurrencyID FROM currency WHERE currencyCode = 'GTQ' LIMIT 1;
    CALL spInsertCountry('Costa Rica', 'CR', 'CRI', crcCurrencyID);
    CALL spInsertCountry('Mexico', 'MX', 'MEX', mxnCurrencyID);
    CALL spInsertCountry('Colombia', 'CO', 'COL', copCurrencyID);
    CALL spInsertCountry('Peru', 'PE', 'PER', penCurrencyID);
    CALL spInsertCountry('Guatemala', 'GT', 'GTM', gtqCurrencyID);
    SELECT countryID INTO costaRicaCountryID FROM country WHERE iso2Code = 'CR' LIMIT 1;
    SELECT countryID INTO mexicoCountryID FROM country WHERE iso2Code = 'MX' LIMIT 1;
    SELECT countryID INTO colombiaCountryID FROM country WHERE iso2Code = 'CO' LIMIT 1;
    SELECT countryID INTO peruCountryID FROM country WHERE iso2Code = 'PE' LIMIT 1;
    SELECT countryID INTO guatemalaCountryID FROM country WHERE iso2Code = 'GT' LIMIT 1;
    CALL spInsertCurrentExchangeRate(1, usdCurrencyID, crcCurrencyID, 510.500000, 515.750000, 'Central Bank CR');
    CALL spInsertCurrentExchangeRate(2, usdCurrencyID, mxnCurrencyID, 17.150000, 17.350000, 'Banxico');
    CALL spInsertCurrentExchangeRate(3, usdCurrencyID, copCurrencyID, 3950.000000, 3985.000000, 'Banco Republica');
    CALL spInsertCurrentExchangeRate(4, usdCurrencyID, penCurrencyID, 3.720000, 3.760000, 'BCRP');
    CALL spInsertCurrentExchangeRate(5, usdCurrencyID, gtqCurrencyID, 7.800000, 7.850000, 'Banguat');
    CALL spInsertBrandTemplate('PUREAURA', 'PureAura', 'https://example.com/pureaura-logo.png', 'Natural wellness for daily life', 'Health-conscious consumers 25-45');
    CALL spInsertBrandTemplate('TERRAVERDE', 'TerraVerde', 'https://example.com/terraverde-logo.png', 'Organic food from earth to table', 'Organic food enthusiasts 30-55');
    CALL spInsertBrandTemplate('AQUAVITA', 'AquaVita', 'https://example.com/aquavita-logo.png', 'Refreshing natural beverages', 'Active lifestyle consumers 20-40');
    CALL spInsertPeople('PERS-ADMIN-001', costaRicaCountryID, 'admin@dynamicbrands.com', 'Carlos', 'Mendez', 'hash_admin_001', 'SYSTEM_USER', adminPersonID);
    CALL spInsertSystemUser(adminPersonID, 'USR-ADMIN-001', 'ADMIN');
    CALL spInsertPeople('PERS-MGR-001', mexicoCountryID, 'manager@dynamicbrands.com', 'Ana', 'Lopez', 'hash_mgr_001', 'SYSTEM_USER', managerPersonID);
    CALL spInsertSystemUser(managerPersonID, 'USR-MGR-001', 'MANAGER');
    CALL spInsertPeople('PERS-CUST-001', costaRicaCountryID, 'laura.ramirez@email.com', 'Laura', 'Ramirez', 'hash_cust_001', 'CUSTOMER', cust1PersonID);
    CALL spInsertPeople('PERS-CUST-002', mexicoCountryID, 'diego.hernandez@email.com', 'Diego', 'Hernandez', 'hash_cust_002', 'CUSTOMER', cust2PersonID);
    CALL spInsertPeople('PERS-CUST-003', colombiaCountryID, 'valentina.castro@email.com', 'Valentina', 'Castro', 'hash_cust_003', 'CUSTOMER', cust3PersonID);
    CALL spInsertPeople('PERS-CUST-004', peruCountryID, 'miguel.flores@email.com', 'Miguel', 'Flores', 'hash_cust_004', 'CUSTOMER', cust4PersonID);
    CALL spInsertPeople('PERS-CUST-005', guatemalaCountryID, 'sofia.morales@email.com', 'Sofia', 'Morales', 'hash_cust_005', 'CUSTOMER', cust5PersonID);
    CALL spInsertDynamicSite('SITE-PA-CR', 'PureAura Costa Rica', 'PUREAURA', costaRicaCountryID, crcCurrencyID, 'ACTIVE', 'pureaura.cr', 'Natural health oils', 'Warm and trustworthy', JSON_OBJECT('primaryColor', '#2E7D32', 'style', 'natural'), 'Dynamic Brands CR', 'https://example.com/pa-cr-logo.png', site1ID);
    CALL spInsertDynamicSite('SITE-PA-MX', 'PureAura Mexico', 'PUREAURA', mexicoCountryID, mxnCurrencyID, 'ACTIVE', 'pureaura.mx', 'Wellness and beauty', 'Fresh and modern', JSON_OBJECT('primaryColor', '#1B5E20', 'style', 'modern'), 'Dynamic Brands MX', 'https://example.com/pa-mx-logo.png', site2ID);
    CALL spInsertDynamicSite('SITE-PA-CO', 'PureAura Colombia', 'PUREAURA', colombiaCountryID, copCurrencyID, 'ACTIVE', 'pureaura.co', 'Essential oils and soaps', 'Elegant and natural', JSON_OBJECT('primaryColor', '#388E3C', 'style', 'elegant'), 'Dynamic Brands CO', 'https://example.com/pa-co-logo.png', site3ID);
    CALL spInsertDynamicSite('SITE-TV-PE', 'TerraVerde Peru', 'TERRAVERDE', peruCountryID, penCurrencyID, 'ACTIVE', 'terraverde.pe', 'Organic superfoods', 'Earthy and authentic', JSON_OBJECT('primaryColor', '#795548', 'style', 'earthy'), 'Dynamic Brands PE', 'https://example.com/tv-pe-logo.png', site4ID);
    CALL spInsertDynamicSite('SITE-TV-GT', 'TerraVerde Guatemala', 'TERRAVERDE', guatemalaCountryID, gtqCurrencyID, 'ACTIVE', 'terraverde.gt', 'Traditional organic food', 'Rustic and warm', JSON_OBJECT('primaryColor', '#6D4C41', 'style', 'rustic'), 'Dynamic Brands GT', 'https://example.com/tv-gt-logo.png', site5ID);
    CALL spInsertDynamicSite('SITE-TV-CR', 'TerraVerde Costa Rica', 'TERRAVERDE', costaRicaCountryID, crcCurrencyID, 'ACTIVE', 'terraverde.cr', 'Farm to table organics', 'Pure and simple', JSON_OBJECT('primaryColor', '#8D6E63', 'style', 'simple'), 'Dynamic Brands CR', 'https://example.com/tv-cr-logo.png', site6ID);
    CALL spInsertDynamicSite('SITE-AV-MX', 'AquaVita Mexico', 'AQUAVITA', mexicoCountryID, mxnCurrencyID, 'ACTIVE', 'aquavita.mx', 'Natural refreshing drinks', 'Vibrant and energetic', JSON_OBJECT('primaryColor', '#0288D1', 'style', 'vibrant'), 'Dynamic Brands MX', 'https://example.com/av-mx-logo.png', site7ID);
    CALL spInsertDynamicSite('SITE-AV-CO', 'AquaVita Colombia', 'AQUAVITA', colombiaCountryID, copCurrencyID, 'ACTIVE', 'aquavita.co', 'Tropical beverages', 'Tropical and fun', JSON_OBJECT('primaryColor', '#0277BD', 'style', 'tropical'), 'Dynamic Brands CO', 'https://example.com/av-co-logo.png', site8ID);
    CALL spInsertDynamicSite('SITE-AV-PE', 'AquaVita Peru', 'AQUAVITA', peruCountryID, penCurrencyID, 'ACTIVE', 'aquavita.pe', 'Andean natural drinks', 'Bold and authentic', JSON_OBJECT('primaryColor', '#01579B', 'style', 'bold'), 'Dynamic Brands PE', 'https://example.com/av-pe-logo.png', site9ID);
    CALL spInsertDynamicSiteMetric(site1ID, 'VISITS', CURRENT_DATE, 1200);
    CALL spInsertDynamicSiteMetric(site1ID, 'PURCHASES', CURRENT_DATE, 48);
    CALL spInsertDynamicSiteMetric(site1ID, 'CONVERSION_RATE', CURRENT_DATE, 0.04);
    CALL spInsertDynamicSiteMetric(site2ID, 'VISITS', CURRENT_DATE, 2500);
    CALL spInsertDynamicSiteMetric(site2ID, 'PURCHASES', CURRENT_DATE, 95);
    CALL spInsertDynamicSiteMetric(site3ID, 'VISITS', CURRENT_DATE, 1800);
    CALL spInsertDynamicSiteMetric(site3ID, 'PURCHASES', CURRENT_DATE, 60);
    CALL spInsertDynamicSiteMetric(site4ID, 'VISITS', CURRENT_DATE, 900);
    CALL spInsertDynamicSiteMetric(site4ID, 'PURCHASES', CURRENT_DATE, 35);
    CALL spInsertDynamicSiteMetric(site5ID, 'VISITS', CURRENT_DATE, 700);
    CALL spInsertDynamicSiteMetric(site5ID, 'PURCHASES', CURRENT_DATE, 22);
    CALL spInsertDynamicSiteMetric(site6ID, 'VISITS', CURRENT_DATE, 1100);
    CALL spInsertDynamicSiteMetric(site6ID, 'PURCHASES', CURRENT_DATE, 42);
    CALL spInsertDynamicSiteMetric(site7ID, 'VISITS', CURRENT_DATE, 3200);
    CALL spInsertDynamicSiteMetric(site7ID, 'PURCHASES', CURRENT_DATE, 150);
    CALL spInsertDynamicSiteMetric(site8ID, 'VISITS', CURRENT_DATE, 2100);
    CALL spInsertDynamicSiteMetric(site8ID, 'PURCHASES', CURRENT_DATE, 85);
    CALL spInsertDynamicSiteMetric(site9ID, 'VISITS', CURRENT_DATE, 1500);
    CALL spInsertDynamicSiteMetric(site9ID, 'PURCHASES', CURRENT_DATE, 55);
    CALL spInsertProduct('PROD-001', site1ID, 'BEVERAGE', 'Infusion de Manzanilla Organica', 'Infusion relajante de manzanilla organica', 'SKU-001', usdCurrencyID, 10.35, adminPersonID, prodID);
    CALL spInsertProductPrice(prodID, site1ID, crcCurrencyID, 5283.68, CURRENT_TIMESTAMP, NULL, TRUE);
    CALL spInsertProductImage(prodID, 'MAIN', 'https://example.com/img/prod-001.png', 1, TRUE);
    CALL spInsertProduct('PROD-002', site1ID, 'FOOD', 'Granola Artesanal con Frutas', 'Granola hecha a mano con frutas secas', 'SKU-002', usdCurrencyID, 11.7, adminPersonID, prodID);
    CALL spInsertProductPrice(prodID, site1ID, crcCurrencyID, 5972.85, CURRENT_TIMESTAMP, NULL, TRUE);
    CALL spInsertProductImage(prodID, 'MAIN', 'https://example.com/img/prod-002.png', 1, TRUE);
    CALL spInsertProduct('PROD-003', site1ID, 'DERM', 'Crema Facial Antioxidante', 'Crema facial con vitamina C y E', 'SKU-003', usdCurrencyID, 12.05, adminPersonID, prodID);
    CALL spInsertProductPrice(prodID, site1ID, crcCurrencyID, 6151.53, CURRENT_TIMESTAMP, NULL, TRUE);
    CALL spInsertProductImage(prodID, 'MAIN', 'https://example.com/img/prod-003.png', 1, TRUE);
    CALL spInsertProduct('PROD-004', site1ID, 'HAIR', 'Acondicionador de Aceite de Argan', 'Acondicionador capilar reparador de argan', 'SKU-004', usdCurrencyID, 13.9, adminPersonID, prodID);
    CALL spInsertProductPrice(prodID, site1ID, crcCurrencyID, 7095.95, CURRENT_TIMESTAMP, NULL, TRUE);
    CALL spInsertProductImage(prodID, 'MAIN', 'https://example.com/img/prod-004.png', 1, TRUE);
    CALL spInsertProduct('PROD-005', site1ID, 'AROMA', 'Aceite Esencial de Lavanda', 'Aceite esencial puro de lavanda para aromaterapia', 'SKU-005', usdCurrencyID, 15.25, adminPersonID, prodID);
    CALL spInsertProductPrice(prodID, site1ID, crcCurrencyID, 7785.12, CURRENT_TIMESTAMP, NULL, TRUE);
    CALL spInsertProductImage(prodID, 'MAIN', 'https://example.com/img/prod-005.png', 1, TRUE);
    CALL spInsertProduct('PROD-006', site1ID, 'SOAP', 'Jabon de Avena y Miel', 'Jabon artesanal de avena y miel natural', 'SKU-006', usdCurrencyID, 18.1, adminPersonID, prodID);
    CALL spInsertProductPrice(prodID, site1ID, crcCurrencyID, 9240.05, CURRENT_TIMESTAMP, NULL, TRUE);
    CALL spInsertProductImage(prodID, 'MAIN', 'https://example.com/img/prod-006.png', 1, TRUE);
    CALL spInsertProduct('PROD-007', site1ID, 'ESSOIL', 'Aceite de Rosa Mosqueta', 'Aceite regenerador de rosa mosqueta', 'SKU-007', usdCurrencyID, 15.95, adminPersonID, prodID);
    CALL spInsertProductPrice(prodID, site1ID, crcCurrencyID, 8142.47, CURRENT_TIMESTAMP, NULL, TRUE);
    CALL spInsertProductImage(prodID, 'MAIN', 'https://example.com/img/prod-007.png', 1, TRUE);
    CALL spInsertProduct('PROD-008', site1ID, 'BEVERAGE', 'Te Verde Organico Premium', 'Te verde organico de hoja entera', 'SKU-008', usdCurrencyID, 16.3, adminPersonID, prodID);
    CALL spInsertProductPrice(prodID, site1ID, crcCurrencyID, 8321.15, CURRENT_TIMESTAMP, NULL, TRUE);
    CALL spInsertProductImage(prodID, 'MAIN', 'https://example.com/img/prod-008.png', 1, TRUE);
    CALL spInsertProduct('PROD-009', site1ID, 'FOOD', 'Miel Organica de Abeja', 'Miel pura organica de abejas silvestres', 'SKU-009', usdCurrencyID, 17.65, adminPersonID, prodID);
    CALL spInsertProductPrice(prodID, site1ID, crcCurrencyID, 9010.32, CURRENT_TIMESTAMP, NULL, TRUE);
    CALL spInsertProductImage(prodID, 'MAIN', 'https://example.com/img/prod-009.png', 1, TRUE);
    CALL spInsertProduct('PROD-010', site1ID, 'DERM', 'Serum de Acido Hialuronico', 'Serum hidratante de acido hialuronico', 'SKU-010', usdCurrencyID, 18.0, adminPersonID, prodID);
    CALL spInsertProductPrice(prodID, site1ID, crcCurrencyID, 9189.0, CURRENT_TIMESTAMP, NULL, TRUE);
    CALL spInsertProductImage(prodID, 'MAIN', 'https://example.com/img/prod-010.png', 1, TRUE);
    CALL spInsertProduct('PROD-011', site1ID, 'HAIR', 'Shampoo de Biotina y Colageno', 'Shampoo fortalecedor con biotina y colageno', 'SKU-011', usdCurrencyID, 19.85, adminPersonID, prodID);
    CALL spInsertProductPrice(prodID, site1ID, crcCurrencyID, 10133.43, CURRENT_TIMESTAMP, NULL, TRUE);
    CALL spInsertProductImage(prodID, 'MAIN', 'https://example.com/img/prod-011.png', 1, TRUE);
    CALL spInsertProduct('PROD-012', site1ID, 'AROMA', 'Aceite Esencial de Eucalipto', 'Aceite esencial de eucalipto para respiracion', 'SKU-012', usdCurrencyID, 21.2, adminPersonID, prodID);
    CALL spInsertProductPrice(prodID, site1ID, crcCurrencyID, 10822.6, CURRENT_TIMESTAMP, NULL, TRUE);
    CALL spInsertProductImage(prodID, 'MAIN', 'https://example.com/img/prod-012.png', 1, TRUE);
    CALL spInsertProduct('PROD-013', site2ID, 'SOAP', 'Jabon de Carbon Activado', 'Jabon facial de carbon activado purificante', 'SKU-013', usdCurrencyID, 24.05, adminPersonID, prodID);
    CALL spInsertProductPrice(prodID, site2ID, mxnCurrencyID, 412.46, CURRENT_TIMESTAMP, NULL, TRUE);
    CALL spInsertProductImage(prodID, 'MAIN', 'https://example.com/img/prod-013.png', 1, TRUE);
    CALL spInsertProduct('PROD-014', site2ID, 'ESSOIL', 'Aceite de Coco Organico', 'Aceite de coco virgen extra organico', 'SKU-014', usdCurrencyID, 21.9, adminPersonID, prodID);
    CALL spInsertProductPrice(prodID, site2ID, mxnCurrencyID, 375.58, CURRENT_TIMESTAMP, NULL, TRUE);
    CALL spInsertProductImage(prodID, 'MAIN', 'https://example.com/img/prod-014.png', 1, TRUE);
    CALL spInsertProduct('PROD-015', site2ID, 'BEVERAGE', 'Jugo Verde Detox', 'Jugo verde prensado en frio detox', 'SKU-015', usdCurrencyID, 22.25, adminPersonID, prodID);
    CALL spInsertProductPrice(prodID, site2ID, mxnCurrencyID, 381.59, CURRENT_TIMESTAMP, NULL, TRUE);
    CALL spInsertProductImage(prodID, 'MAIN', 'https://example.com/img/prod-015.png', 1, TRUE);
    CALL spInsertProduct('PROD-016', site2ID, 'FOOD', 'Quinoa Organica Premium', 'Quinoa blanca organica de los Andes', 'SKU-016', usdCurrencyID, 23.6, adminPersonID, prodID);
    CALL spInsertProductPrice(prodID, site2ID, mxnCurrencyID, 404.74, CURRENT_TIMESTAMP, NULL, TRUE);
    CALL spInsertProductImage(prodID, 'MAIN', 'https://example.com/img/prod-016.png', 1, TRUE);
    CALL spInsertProduct('PROD-017', site2ID, 'DERM', 'Mascarilla de Arcilla Verde', 'Mascarilla purificante de arcilla verde', 'SKU-017', usdCurrencyID, 23.95, adminPersonID, prodID);
    CALL spInsertProductPrice(prodID, site2ID, mxnCurrencyID, 410.74, CURRENT_TIMESTAMP, NULL, TRUE);
    CALL spInsertProductImage(prodID, 'MAIN', 'https://example.com/img/prod-017.png', 1, TRUE);
    CALL spInsertProduct('PROD-018', site2ID, 'HAIR', 'Aceite Capilar de Jojoba', 'Aceite nutritivo para puntas danadas', 'SKU-018', usdCurrencyID, 25.8, adminPersonID, prodID);
    CALL spInsertProductPrice(prodID, site2ID, mxnCurrencyID, 442.47, CURRENT_TIMESTAMP, NULL, TRUE);
    CALL spInsertProductImage(prodID, 'MAIN', 'https://example.com/img/prod-018.png', 1, TRUE);
    CALL spInsertProduct('PROD-019', site2ID, 'AROMA', 'Aceite Esencial de Menta', 'Aceite esencial de menta refrescante', 'SKU-019', usdCurrencyID, 27.15, adminPersonID, prodID);
    CALL spInsertProductPrice(prodID, site2ID, mxnCurrencyID, 465.62, CURRENT_TIMESTAMP, NULL, TRUE);
    CALL spInsertProductImage(prodID, 'MAIN', 'https://example.com/img/prod-019.png', 1, TRUE);
    CALL spInsertProduct('PROD-020', site2ID, 'SOAP', 'Jabon de Aloe Vera', 'Jabon hidratante de aloe vera natural', 'SKU-020', usdCurrencyID, 30.0, adminPersonID, prodID);
    CALL spInsertProductPrice(prodID, site2ID, mxnCurrencyID, 514.5, CURRENT_TIMESTAMP, NULL, TRUE);
    CALL spInsertProductImage(prodID, 'MAIN', 'https://example.com/img/prod-020.png', 1, TRUE);
    CALL spInsertProduct('PROD-021', site2ID, 'ESSOIL', 'Aceite de Almendras Dulces', 'Aceite hidratante de almendras dulces', 'SKU-021', usdCurrencyID, 27.85, adminPersonID, prodID);
    CALL spInsertProductPrice(prodID, site2ID, mxnCurrencyID, 477.63, CURRENT_TIMESTAMP, NULL, TRUE);
    CALL spInsertProductImage(prodID, 'MAIN', 'https://example.com/img/prod-021.png', 1, TRUE);
    CALL spInsertProduct('PROD-022', site2ID, 'BEVERAGE', 'Kombucha de Jengibre', 'Kombucha artesanal de jengibre', 'SKU-022', usdCurrencyID, 28.2, adminPersonID, prodID);
    CALL spInsertProductPrice(prodID, site2ID, mxnCurrencyID, 483.63, CURRENT_TIMESTAMP, NULL, TRUE);
    CALL spInsertProductImage(prodID, 'MAIN', 'https://example.com/img/prod-022.png', 1, TRUE);
    CALL spInsertProduct('PROD-023', site2ID, 'FOOD', 'Cacao en Polvo Crudo', 'Cacao crudo organico en polvo', 'SKU-023', usdCurrencyID, 29.55, adminPersonID, prodID);
    CALL spInsertProductPrice(prodID, site2ID, mxnCurrencyID, 506.78, CURRENT_TIMESTAMP, NULL, TRUE);
    CALL spInsertProductImage(prodID, 'MAIN', 'https://example.com/img/prod-023.png', 1, TRUE);
    CALL spInsertProduct('PROD-024', site3ID, 'DERM', 'Protector Solar Natural SPF30', 'Protector solar con ingredientes naturales', 'SKU-024', usdCurrencyID, 29.9, adminPersonID, prodID);
    CALL spInsertProductPrice(prodID, site3ID, copCurrencyID, 118105.0, CURRENT_TIMESTAMP, NULL, TRUE);
    CALL spInsertProductImage(prodID, 'MAIN', 'https://example.com/img/prod-024.png', 1, TRUE);
    CALL spInsertProduct('PROD-025', site3ID, 'HAIR', 'Mascarilla Capilar de Coco', 'Mascarilla reparadora de coco para cabello', 'SKU-025', usdCurrencyID, 31.75, adminPersonID, prodID);
    CALL spInsertProductPrice(prodID, site3ID, copCurrencyID, 125412.5, CURRENT_TIMESTAMP, NULL, TRUE);
    CALL spInsertProductImage(prodID, 'MAIN', 'https://example.com/img/prod-025.png', 1, TRUE);
    CALL spInsertProduct('PROD-026', site3ID, 'AROMA', 'Aceite Esencial de Naranja', 'Aceite esencial de naranja dulce energizante', 'SKU-026', usdCurrencyID, 33.1, adminPersonID, prodID);
    CALL spInsertProductPrice(prodID, site3ID, copCurrencyID, 130745.0, CURRENT_TIMESTAMP, NULL, TRUE);
    CALL spInsertProductImage(prodID, 'MAIN', 'https://example.com/img/prod-026.png', 1, TRUE);
    CALL spInsertProduct('PROD-027', site3ID, 'SOAP', 'Jabon de Calendula', 'Jabon suave de calendula para piel sensible', 'SKU-027', usdCurrencyID, 35.95, adminPersonID, prodID);
    CALL spInsertProductPrice(prodID, site3ID, copCurrencyID, 142002.5, CURRENT_TIMESTAMP, NULL, TRUE);
    CALL spInsertProductImage(prodID, 'MAIN', 'https://example.com/img/prod-027.png', 1, TRUE);
    CALL spInsertProduct('PROD-028', site3ID, 'ESSOIL', 'Aceite de Semilla de Uva', 'Aceite ligero de semilla de uva para piel', 'SKU-028', usdCurrencyID, 33.8, adminPersonID, prodID);
    CALL spInsertProductPrice(prodID, site3ID, copCurrencyID, 133510.0, CURRENT_TIMESTAMP, NULL, TRUE);
    CALL spInsertProductImage(prodID, 'MAIN', 'https://example.com/img/prod-028.png', 1, TRUE);
    CALL spInsertProduct('PROD-029', site3ID, 'BEVERAGE', 'Agua de Horchata Natural', 'Agua de horchata de arroz tradicional', 'SKU-029', usdCurrencyID, 34.15, adminPersonID, prodID);
    CALL spInsertProductPrice(prodID, site3ID, copCurrencyID, 134892.5, CURRENT_TIMESTAMP, NULL, TRUE);
    CALL spInsertProductImage(prodID, 'MAIN', 'https://example.com/img/prod-029.png', 1, TRUE);
    CALL spInsertProduct('PROD-030', site3ID, 'FOOD', 'Semillas de Chia Organicas', 'Semillas de chia premium organicas', 'SKU-030', usdCurrencyID, 35.5, adminPersonID, prodID);
    CALL spInsertProductPrice(prodID, site3ID, copCurrencyID, 140225.0, CURRENT_TIMESTAMP, NULL, TRUE);
    CALL spInsertProductImage(prodID, 'MAIN', 'https://example.com/img/prod-030.png', 1, TRUE);
    CALL spInsertProduct('PROD-031', site3ID, 'DERM', 'Crema de Manos de Rosa', 'Crema reparadora de manos con rosa', 'SKU-031', usdCurrencyID, 35.85, adminPersonID, prodID);
    CALL spInsertProductPrice(prodID, site3ID, copCurrencyID, 141607.5, CURRENT_TIMESTAMP, NULL, TRUE);
    CALL spInsertProductImage(prodID, 'MAIN', 'https://example.com/img/prod-031.png', 1, TRUE);
    CALL spInsertProduct('PROD-032', site3ID, 'HAIR', 'Tonico Anticaida Natural', 'Tonico capilar anticaida con romero', 'SKU-032', usdCurrencyID, 37.7, adminPersonID, prodID);
    CALL spInsertProductPrice(prodID, site3ID, copCurrencyID, 148915.0, CURRENT_TIMESTAMP, NULL, TRUE);
    CALL spInsertProductImage(prodID, 'MAIN', 'https://example.com/img/prod-032.png', 1, TRUE);
    CALL spInsertProduct('PROD-033', site3ID, 'AROMA', 'Aceite Esencial de Canela', 'Aceite esencial de canela reconfortante', 'SKU-033', usdCurrencyID, 39.05, adminPersonID, prodID);
    CALL spInsertProductPrice(prodID, site3ID, copCurrencyID, 154247.5, CURRENT_TIMESTAMP, NULL, TRUE);
    CALL spInsertProductImage(prodID, 'MAIN', 'https://example.com/img/prod-033.png', 1, TRUE);
    CALL spInsertProduct('PROD-034', site3ID, 'SOAP', 'Jabon de Romero', 'Jabon artesanal de romero estimulante', 'SKU-034', usdCurrencyID, 41.9, adminPersonID, prodID);
    CALL spInsertProductPrice(prodID, site3ID, copCurrencyID, 165505.0, CURRENT_TIMESTAMP, NULL, TRUE);
    CALL spInsertProductImage(prodID, 'MAIN', 'https://example.com/img/prod-034.png', 1, TRUE);
    CALL spInsertProduct('PROD-035', site4ID, 'ESSOIL', 'Aceite de Aguacate Prensado en Frio', 'Aceite nutritivo de aguacate para piel', 'SKU-035', usdCurrencyID, 39.75, adminPersonID, prodID);
    CALL spInsertProductPrice(prodID, site4ID, penCurrencyID, 147.87, CURRENT_TIMESTAMP, NULL, TRUE);
    CALL spInsertProductImage(prodID, 'MAIN', 'https://example.com/img/prod-035.png', 1, TRUE);
    CALL spInsertProduct('PROD-036', site4ID, 'BEVERAGE', 'Chicha Morada Concentrada', 'Concentrado natural de chicha morada', 'SKU-036', usdCurrencyID, 40.1, adminPersonID, prodID);
    CALL spInsertProductPrice(prodID, site4ID, penCurrencyID, 149.17, CURRENT_TIMESTAMP, NULL, TRUE);
    CALL spInsertProductImage(prodID, 'MAIN', 'https://example.com/img/prod-036.png', 1, TRUE);
    CALL spInsertProduct('PROD-037', site4ID, 'FOOD', 'Maca en Polvo Gelatinizada', 'Maca peruana gelatinizada en polvo', 'SKU-037', usdCurrencyID, 41.45, adminPersonID, prodID);
    CALL spInsertProductPrice(prodID, site4ID, penCurrencyID, 154.19, CURRENT_TIMESTAMP, NULL, TRUE);
    CALL spInsertProductImage(prodID, 'MAIN', 'https://example.com/img/prod-037.png', 1, TRUE);
    CALL spInsertProduct('PROD-038', site4ID, 'DERM', 'Tonico Facial de Hamamelis', 'Tonico astringente natural de hamamelis', 'SKU-038', usdCurrencyID, 41.8, adminPersonID, prodID);
    CALL spInsertProductPrice(prodID, site4ID, penCurrencyID, 155.5, CURRENT_TIMESTAMP, NULL, TRUE);
    CALL spInsertProductImage(prodID, 'MAIN', 'https://example.com/img/prod-038.png', 1, TRUE);
    CALL spInsertProduct('PROD-039', site4ID, 'HAIR', 'Serum Capilar de Keratina', 'Serum reconstructor con keratina vegetal', 'SKU-039', usdCurrencyID, 43.65, adminPersonID, prodID);
    CALL spInsertProductPrice(prodID, site4ID, penCurrencyID, 162.38, CURRENT_TIMESTAMP, NULL, TRUE);
    CALL spInsertProductImage(prodID, 'MAIN', 'https://example.com/img/prod-039.png', 1, TRUE);
    CALL spInsertProduct('PROD-040', site4ID, 'AROMA', 'Vela Aromatica de Vainilla', 'Vela de cera de soja con aroma de vainilla', 'SKU-040', usdCurrencyID, 45.0, adminPersonID, prodID);
    CALL spInsertProductPrice(prodID, site4ID, penCurrencyID, 167.4, CURRENT_TIMESTAMP, NULL, TRUE);
    CALL spInsertProductImage(prodID, 'MAIN', 'https://example.com/img/prod-040.png', 1, TRUE);
    CALL spInsertProduct('PROD-041', site4ID, 'SOAP', 'Jabon de Leche de Cabra', 'Jabon hidratante de leche de cabra', 'SKU-041', usdCurrencyID, 47.85, adminPersonID, prodID);
    CALL spInsertProductPrice(prodID, site4ID, penCurrencyID, 178.0, CURRENT_TIMESTAMP, NULL, TRUE);
    CALL spInsertProductImage(prodID, 'MAIN', 'https://example.com/img/prod-041.png', 1, TRUE);
    CALL spInsertProduct('PROD-042', site4ID, 'ESSOIL', 'Aceite de Sacha Inchi', 'Aceite omega-3 de sacha inchi peruano', 'SKU-042', usdCurrencyID, 45.7, adminPersonID, prodID);
    CALL spInsertProductPrice(prodID, site4ID, penCurrencyID, 170.0, CURRENT_TIMESTAMP, NULL, TRUE);
    CALL spInsertProductImage(prodID, 'MAIN', 'https://example.com/img/prod-042.png', 1, TRUE);
    CALL spInsertProduct('PROD-043', site4ID, 'BEVERAGE', 'Te de Munia Andino', 'Infusion de hierbas andinas relajante', 'SKU-043', usdCurrencyID, 46.05, adminPersonID, prodID);
    CALL spInsertProductPrice(prodID, site4ID, penCurrencyID, 171.31, CURRENT_TIMESTAMP, NULL, TRUE);
    CALL spInsertProductImage(prodID, 'MAIN', 'https://example.com/img/prod-043.png', 1, TRUE);
    CALL spInsertProduct('PROD-044', site4ID, 'FOOD', 'Chocolate Artesanal 70%', 'Chocolate oscuro artesanal 70% cacao', 'SKU-044', usdCurrencyID, 47.4, adminPersonID, prodID);
    CALL spInsertProductPrice(prodID, site4ID, penCurrencyID, 176.33, CURRENT_TIMESTAMP, NULL, TRUE);
    CALL spInsertProductImage(prodID, 'MAIN', 'https://example.com/img/prod-044.png', 1, TRUE);
    CALL spInsertProduct('PROD-045', site4ID, 'DERM', 'Gel de Sabila Puro', 'Gel de aloe vera 100% natural', 'SKU-045', usdCurrencyID, 47.75, adminPersonID, prodID);
    CALL spInsertProductPrice(prodID, site4ID, penCurrencyID, 177.63, CURRENT_TIMESTAMP, NULL, TRUE);
    CALL spInsertProductImage(prodID, 'MAIN', 'https://example.com/img/prod-045.png', 1, TRUE);
    CALL spInsertProduct('PROD-046', site5ID, 'HAIR', 'Aceite de Ricino para Cabello', 'Aceite de ricino fortalecedor capilar', 'SKU-046', usdCurrencyID, 49.6, adminPersonID, prodID);
    CALL spInsertProductPrice(prodID, site5ID, gtqCurrencyID, 386.88, CURRENT_TIMESTAMP, NULL, TRUE);
    CALL spInsertProductImage(prodID, 'MAIN', 'https://example.com/img/prod-046.png', 1, TRUE);
    CALL spInsertProduct('PROD-047', site5ID, 'AROMA', 'Incienso de Sandalo Natural', 'Varillas de incienso de sandalo', 'SKU-047', usdCurrencyID, 50.95, adminPersonID, prodID);
    CALL spInsertProductPrice(prodID, site5ID, gtqCurrencyID, 397.41, CURRENT_TIMESTAMP, NULL, TRUE);
    CALL spInsertProductImage(prodID, 'MAIN', 'https://example.com/img/prod-047.png', 1, TRUE);
    CALL spInsertProduct('PROD-048', site5ID, 'SOAP', 'Jabon de Cacao y Vainilla', 'Jabon artesanal de cacao y vainilla', 'SKU-048', usdCurrencyID, 53.8, adminPersonID, prodID);
    CALL spInsertProductPrice(prodID, site5ID, gtqCurrencyID, 419.64, CURRENT_TIMESTAMP, NULL, TRUE);
    CALL spInsertProductImage(prodID, 'MAIN', 'https://example.com/img/prod-048.png', 1, TRUE);
    CALL spInsertProduct('PROD-049', site5ID, 'ESSOIL', 'Aceite Esencial de Limoncillo', 'Aceite esencial de lemongrass', 'SKU-049', usdCurrencyID, 51.65, adminPersonID, prodID);
    CALL spInsertProductPrice(prodID, site5ID, gtqCurrencyID, 402.87, CURRENT_TIMESTAMP, NULL, TRUE);
    CALL spInsertProductImage(prodID, 'MAIN', 'https://example.com/img/prod-049.png', 1, TRUE);
    CALL spInsertProduct('PROD-050', site5ID, 'BEVERAGE', 'Agua de Jamaica Premium', 'Agua de jamaica con flor seleccionada', 'SKU-050', usdCurrencyID, 52.0, adminPersonID, prodID);
    CALL spInsertProductPrice(prodID, site5ID, gtqCurrencyID, 405.6, CURRENT_TIMESTAMP, NULL, TRUE);
    CALL spInsertProductImage(prodID, 'MAIN', 'https://example.com/img/prod-050.png', 1, TRUE);
    CALL spInsertProduct('PROD-051', site5ID, 'FOOD', 'Cafe Organico de Altura', 'Cafe gourmet organico de altura', 'SKU-051', usdCurrencyID, 53.35, adminPersonID, prodID);
    CALL spInsertProductPrice(prodID, site5ID, gtqCurrencyID, 416.13, CURRENT_TIMESTAMP, NULL, TRUE);
    CALL spInsertProductImage(prodID, 'MAIN', 'https://example.com/img/prod-051.png', 1, TRUE);
    CALL spInsertProduct('PROD-052', site5ID, 'DERM', 'Exfoliante Corporal de Sal Marina', 'Exfoliante natural de sal marina y aceites', 'SKU-052', usdCurrencyID, 53.7, adminPersonID, prodID);
    CALL spInsertProductPrice(prodID, site5ID, gtqCurrencyID, 418.86, CURRENT_TIMESTAMP, NULL, TRUE);
    CALL spInsertProductImage(prodID, 'MAIN', 'https://example.com/img/prod-052.png', 1, TRUE);
    CALL spInsertProduct('PROD-053', site5ID, 'HAIR', 'Spray Protector Termico', 'Spray protector termico con aceite de argan', 'SKU-053', usdCurrencyID, 55.55, adminPersonID, prodID);
    CALL spInsertProductPrice(prodID, site5ID, gtqCurrencyID, 433.29, CURRENT_TIMESTAMP, NULL, TRUE);
    CALL spInsertProductImage(prodID, 'MAIN', 'https://example.com/img/prod-053.png', 1, TRUE);
    CALL spInsertProduct('PROD-054', site5ID, 'AROMA', 'Difusor de Aceites Esenciales', 'Set difusor con aceites esenciales variados', 'SKU-054', usdCurrencyID, 56.9, adminPersonID, prodID);
    CALL spInsertProductPrice(prodID, site5ID, gtqCurrencyID, 443.82, CURRENT_TIMESTAMP, NULL, TRUE);
    CALL spInsertProductImage(prodID, 'MAIN', 'https://example.com/img/prod-054.png', 1, TRUE);
    CALL spInsertProduct('PROD-055', site5ID, 'SOAP', 'Jabon Exfoliante de Cafe', 'Jabon exfoliante artesanal con cafe', 'SKU-055', usdCurrencyID, 59.75, adminPersonID, prodID);
    CALL spInsertProductPrice(prodID, site5ID, gtqCurrencyID, 466.05, CURRENT_TIMESTAMP, NULL, TRUE);
    CALL spInsertProductImage(prodID, 'MAIN', 'https://example.com/img/prod-055.png', 1, TRUE);
    CALL spInsertProduct('PROD-056', site5ID, 'ESSOIL', 'Aceite de Argan Premium', 'Aceite de argan puro para cabello y piel', 'SKU-056', usdCurrencyID, 57.6, adminPersonID, prodID);
    CALL spInsertProductPrice(prodID, site5ID, gtqCurrencyID, 449.28, CURRENT_TIMESTAMP, NULL, TRUE);
    CALL spInsertProductImage(prodID, 'MAIN', 'https://example.com/img/prod-056.png', 1, TRUE);
    CALL spInsertProduct('PROD-057', site6ID, 'BEVERAGE', 'Jugo de Camu Camu', 'Jugo de camu camu alto en vitamina C', 'SKU-057', usdCurrencyID, 57.95, adminPersonID, prodID);
    CALL spInsertProductPrice(prodID, site6ID, crcCurrencyID, 29583.48, CURRENT_TIMESTAMP, NULL, TRUE);
    CALL spInsertProductImage(prodID, 'MAIN', 'https://example.com/img/prod-057.png', 1, TRUE);
    CALL spInsertProduct('PROD-058', site6ID, 'FOOD', 'Lucuma en Polvo', 'Polvo de lucuma peruana para smoothies', 'SKU-058', usdCurrencyID, 59.3, adminPersonID, prodID);
    CALL spInsertProductPrice(prodID, site6ID, crcCurrencyID, 30272.65, CURRENT_TIMESTAMP, NULL, TRUE);
    CALL spInsertProductImage(prodID, 'MAIN', 'https://example.com/img/prod-058.png', 1, TRUE);
    CALL spInsertProduct('PROD-059', site6ID, 'DERM', 'Desodorante Natural de Coco', 'Desodorante sin aluminio de coco', 'SKU-059', usdCurrencyID, 59.65, adminPersonID, prodID);
    CALL spInsertProductPrice(prodID, site6ID, crcCurrencyID, 30451.33, CURRENT_TIMESTAMP, NULL, TRUE);
    CALL spInsertProductImage(prodID, 'MAIN', 'https://example.com/img/prod-059.png', 1, TRUE);
    CALL spInsertProduct('PROD-060', site6ID, 'HAIR', 'Balsamo Desenredante Natural', 'Balsamo desenredante con aceites vegetales', 'SKU-060', usdCurrencyID, 61.5, adminPersonID, prodID);
    CALL spInsertProductPrice(prodID, site6ID, crcCurrencyID, 31395.75, CURRENT_TIMESTAMP, NULL, TRUE);
    CALL spInsertProductImage(prodID, 'MAIN', 'https://example.com/img/prod-060.png', 1, TRUE);
    CALL spInsertProduct('PROD-061', site6ID, 'AROMA', 'Aceite Esencial de Romero', 'Aceite esencial de romero estimulante', 'SKU-061', usdCurrencyID, 62.85, adminPersonID, prodID);
    CALL spInsertProductPrice(prodID, site6ID, crcCurrencyID, 32084.92, CURRENT_TIMESTAMP, NULL, TRUE);
    CALL spInsertProductImage(prodID, 'MAIN', 'https://example.com/img/prod-061.png', 1, TRUE);
    CALL spInsertProduct('PROD-062', site6ID, 'SOAP', 'Jabon de Arcilla Blanca', 'Jabon purificante de arcilla blanca', 'SKU-062', usdCurrencyID, 65.7, adminPersonID, prodID);
    CALL spInsertProductPrice(prodID, site6ID, crcCurrencyID, 33539.85, CURRENT_TIMESTAMP, NULL, TRUE);
    CALL spInsertProductImage(prodID, 'MAIN', 'https://example.com/img/prod-062.png', 1, TRUE);
    CALL spInsertProduct('PROD-063', site6ID, 'ESSOIL', 'Aceite de Jojoba Puro', 'Aceite de jojoba para piel y cabello', 'SKU-063', usdCurrencyID, 63.55, adminPersonID, prodID);
    CALL spInsertProductPrice(prodID, site6ID, crcCurrencyID, 32442.27, CURRENT_TIMESTAMP, NULL, TRUE);
    CALL spInsertProductImage(prodID, 'MAIN', 'https://example.com/img/prod-063.png', 1, TRUE);
    CALL spInsertProduct('PROD-064', site6ID, 'BEVERAGE', 'Limonada con Chia', 'Limonada natural con semillas de chia', 'SKU-064', usdCurrencyID, 63.9, adminPersonID, prodID);
    CALL spInsertProductPrice(prodID, site6ID, crcCurrencyID, 32620.95, CURRENT_TIMESTAMP, NULL, TRUE);
    CALL spInsertProductImage(prodID, 'MAIN', 'https://example.com/img/prod-064.png', 1, TRUE);
    CALL spInsertProduct('PROD-065', site6ID, 'FOOD', 'Mermelada de Guayaba', 'Mermelada artesanal de guayaba', 'SKU-065', usdCurrencyID, 65.25, adminPersonID, prodID);
    CALL spInsertProductPrice(prodID, site6ID, crcCurrencyID, 33310.12, CURRENT_TIMESTAMP, NULL, TRUE);
    CALL spInsertProductImage(prodID, 'MAIN', 'https://example.com/img/prod-065.png', 1, TRUE);
    CALL spInsertProduct('PROD-066', site6ID, 'DERM', 'Crema Corporal de Karite', 'Crema hidratante corporal de manteca de karite', 'SKU-066', usdCurrencyID, 65.6, adminPersonID, prodID);
    CALL spInsertProductPrice(prodID, site6ID, crcCurrencyID, 33488.8, CURRENT_TIMESTAMP, NULL, TRUE);
    CALL spInsertProductImage(prodID, 'MAIN', 'https://example.com/img/prod-066.png', 1, TRUE);
    CALL spInsertProduct('PROD-067', site6ID, 'HAIR', 'Ampolla Capilar Reparadora', 'Ampolla de tratamiento capilar intensivo', 'SKU-067', usdCurrencyID, 67.45, adminPersonID, prodID);
    CALL spInsertProductPrice(prodID, site6ID, crcCurrencyID, 34433.22, CURRENT_TIMESTAMP, NULL, TRUE);
    CALL spInsertProductImage(prodID, 'MAIN', 'https://example.com/img/prod-067.png', 1, TRUE);
    CALL spInsertProduct('PROD-068', site7ID, 'AROMA', 'Sachet Aromatico de Lavanda', 'Saco aromatico de lavanda seca', 'SKU-068', usdCurrencyID, 68.8, adminPersonID, prodID);
    CALL spInsertProductPrice(prodID, site7ID, mxnCurrencyID, 1179.92, CURRENT_TIMESTAMP, NULL, TRUE);
    CALL spInsertProductImage(prodID, 'MAIN', 'https://example.com/img/prod-068.png', 1, TRUE);
    CALL spInsertProduct('PROD-069', site7ID, 'SOAP', 'Jabon de Manzanilla', 'Jabon calmante de manzanilla para bebe', 'SKU-069', usdCurrencyID, 71.65, adminPersonID, prodID);
    CALL spInsertProductPrice(prodID, site7ID, mxnCurrencyID, 1228.8, CURRENT_TIMESTAMP, NULL, TRUE);
    CALL spInsertProductImage(prodID, 'MAIN', 'https://example.com/img/prod-069.png', 1, TRUE);
    CALL spInsertProduct('PROD-070', site7ID, 'ESSOIL', 'Aceite Corporal de Coco y Vainilla', 'Aceite corporal hidratante tropical', 'SKU-070', usdCurrencyID, 69.5, adminPersonID, prodID);
    CALL spInsertProductPrice(prodID, site7ID, mxnCurrencyID, 1191.92, CURRENT_TIMESTAMP, NULL, TRUE);
    CALL spInsertProductImage(prodID, 'MAIN', 'https://example.com/img/prod-070.png', 1, TRUE);
    CALL spInsertProduct('PROD-071', site7ID, 'BEVERAGE', 'Te Matcha Organico', 'Te matcha japones grado ceremonial', 'SKU-071', usdCurrencyID, 69.85, adminPersonID, prodID);
    CALL spInsertProductPrice(prodID, site7ID, mxnCurrencyID, 1197.93, CURRENT_TIMESTAMP, NULL, TRUE);
    CALL spInsertProductImage(prodID, 'MAIN', 'https://example.com/img/prod-071.png', 1, TRUE);
    CALL spInsertProduct('PROD-072', site7ID, 'FOOD', 'Cardamomo Premium', 'Cardamomo entero de Alta Verapaz', 'SKU-072', usdCurrencyID, 71.2, adminPersonID, prodID);
    CALL spInsertProductPrice(prodID, site7ID, mxnCurrencyID, 1221.08, CURRENT_TIMESTAMP, NULL, TRUE);
    CALL spInsertProductImage(prodID, 'MAIN', 'https://example.com/img/prod-072.png', 1, TRUE);
    CALL spInsertProduct('PROD-073', site7ID, 'DERM', 'Balsamo Labial de Menta', 'Balsamo labial natural de menta', 'SKU-073', usdCurrencyID, 71.55, adminPersonID, prodID);
    CALL spInsertProductPrice(prodID, site7ID, mxnCurrencyID, 1227.08, CURRENT_TIMESTAMP, NULL, TRUE);
    CALL spInsertProductImage(prodID, 'MAIN', 'https://example.com/img/prod-073.png', 1, TRUE);
    CALL spInsertProduct('PROD-074', site7ID, 'HAIR', 'Gel Fijador Natural', 'Gel fijador de cabello con extractos naturales', 'SKU-074', usdCurrencyID, 73.4, adminPersonID, prodID);
    CALL spInsertProductPrice(prodID, site7ID, mxnCurrencyID, 1258.81, CURRENT_TIMESTAMP, NULL, TRUE);
    CALL spInsertProductImage(prodID, 'MAIN', 'https://example.com/img/prod-074.png', 1, TRUE);
    CALL spInsertProduct('PROD-075', site7ID, 'AROMA', 'Aceite Esencial de Ylang Ylang', 'Aceite esencial floral de ylang ylang', 'SKU-075', usdCurrencyID, 74.75, adminPersonID, prodID);
    CALL spInsertProductPrice(prodID, site7ID, mxnCurrencyID, 1281.96, CURRENT_TIMESTAMP, NULL, TRUE);
    CALL spInsertProductImage(prodID, 'MAIN', 'https://example.com/img/prod-075.png', 1, TRUE);
    CALL spInsertProduct('PROD-076', site7ID, 'SOAP', 'Jabon de Curcuma y Miel', 'Jabon artesanal de curcuma con miel', 'SKU-076', usdCurrencyID, 77.6, adminPersonID, prodID);
    CALL spInsertProductPrice(prodID, site7ID, mxnCurrencyID, 1330.84, CURRENT_TIMESTAMP, NULL, TRUE);
    CALL spInsertProductImage(prodID, 'MAIN', 'https://example.com/img/prod-076.png', 1, TRUE);
    CALL spInsertProduct('PROD-077', site7ID, 'ESSOIL', 'Aceite de Oregano Silvestre', 'Aceite de oregano silvestre medicinal', 'SKU-077', usdCurrencyID, 75.45, adminPersonID, prodID);
    CALL spInsertProductPrice(prodID, site7ID, mxnCurrencyID, 1293.97, CURRENT_TIMESTAMP, NULL, TRUE);
    CALL spInsertProductImage(prodID, 'MAIN', 'https://example.com/img/prod-077.png', 1, TRUE);
    CALL spInsertProduct('PROD-078', site7ID, 'BEVERAGE', 'Agua de Tamarindo', 'Agua fresca de tamarindo natural', 'SKU-078', usdCurrencyID, 75.8, adminPersonID, prodID);
    CALL spInsertProductPrice(prodID, site7ID, mxnCurrencyID, 1299.97, CURRENT_TIMESTAMP, NULL, TRUE);
    CALL spInsertProductImage(prodID, 'MAIN', 'https://example.com/img/prod-078.png', 1, TRUE);
    CALL spInsertProduct('PROD-079', site8ID, 'FOOD', 'Panela Granulada Organica', 'Panela organica granulada artesanal', 'SKU-079', usdCurrencyID, 77.15, adminPersonID, prodID);
    CALL spInsertProductPrice(prodID, site8ID, copCurrencyID, 304742.5, CURRENT_TIMESTAMP, NULL, TRUE);
    CALL spInsertProductImage(prodID, 'MAIN', 'https://example.com/img/prod-079.png', 1, TRUE);
    CALL spInsertProduct('PROD-080', site8ID, 'DERM', 'Contorno de Ojos Antiedad', 'Contorno de ojos con retinol natural', 'SKU-080', usdCurrencyID, 77.5, adminPersonID, prodID);
    CALL spInsertProductPrice(prodID, site8ID, copCurrencyID, 306125.0, CURRENT_TIMESTAMP, NULL, TRUE);
    CALL spInsertProductImage(prodID, 'MAIN', 'https://example.com/img/prod-080.png', 1, TRUE);
    CALL spInsertProduct('PROD-081', site8ID, 'HAIR', 'Aceite de Coco para Cabello', 'Aceite de coco capilar multiusos', 'SKU-081', usdCurrencyID, 79.35, adminPersonID, prodID);
    CALL spInsertProductPrice(prodID, site8ID, copCurrencyID, 313432.5, CURRENT_TIMESTAMP, NULL, TRUE);
    CALL spInsertProductImage(prodID, 'MAIN', 'https://example.com/img/prod-081.png', 1, TRUE);
    CALL spInsertProduct('PROD-082', site8ID, 'AROMA', 'Spray Ambiental de Citricos', 'Spray ambiental natural de citricos', 'SKU-082', usdCurrencyID, 80.7, adminPersonID, prodID);
    CALL spInsertProductPrice(prodID, site8ID, copCurrencyID, 318765.0, CURRENT_TIMESTAMP, NULL, TRUE);
    CALL spInsertProductImage(prodID, 'MAIN', 'https://example.com/img/prod-082.png', 1, TRUE);
    CALL spInsertProduct('PROD-083', site8ID, 'SOAP', 'Jabon de Neem', 'Jabon antibacterial natural de neem', 'SKU-083', usdCurrencyID, 83.55, adminPersonID, prodID);
    CALL spInsertProductPrice(prodID, site8ID, copCurrencyID, 330022.5, CURRENT_TIMESTAMP, NULL, TRUE);
    CALL spInsertProductImage(prodID, 'MAIN', 'https://example.com/img/prod-083.png', 1, TRUE);
    CALL spInsertProduct('PROD-084', site8ID, 'ESSOIL', 'Aceite de Moringa', 'Aceite nutritivo de semilla de moringa', 'SKU-084', usdCurrencyID, 81.4, adminPersonID, prodID);
    CALL spInsertProductPrice(prodID, site8ID, copCurrencyID, 321530.0, CURRENT_TIMESTAMP, NULL, TRUE);
    CALL spInsertProductImage(prodID, 'MAIN', 'https://example.com/img/prod-084.png', 1, TRUE);
    CALL spInsertProduct('PROD-085', site8ID, 'BEVERAGE', 'Jugo de Mora Andina', 'Jugo de mora de castilla andina', 'SKU-085', usdCurrencyID, 81.75, adminPersonID, prodID);
    CALL spInsertProductPrice(prodID, site8ID, copCurrencyID, 322912.5, CURRENT_TIMESTAMP, NULL, TRUE);
    CALL spInsertProductImage(prodID, 'MAIN', 'https://example.com/img/prod-085.png', 1, TRUE);
    CALL spInsertProduct('PROD-086', site8ID, 'FOOD', 'Mantequilla de Mani Artesanal', 'Mantequilla de mani sin azucar anadida', 'SKU-086', usdCurrencyID, 83.1, adminPersonID, prodID);
    CALL spInsertProductPrice(prodID, site8ID, copCurrencyID, 328245.0, CURRENT_TIMESTAMP, NULL, TRUE);
    CALL spInsertProductImage(prodID, 'MAIN', 'https://example.com/img/prod-086.png', 1, TRUE);
    CALL spInsertProduct('PROD-087', site8ID, 'DERM', 'Mascarilla Facial de Miel', 'Mascarilla nutritiva de miel y propoleo', 'SKU-087', usdCurrencyID, 83.45, adminPersonID, prodID);
    CALL spInsertProductPrice(prodID, site8ID, copCurrencyID, 329627.5, CURRENT_TIMESTAMP, NULL, TRUE);
    CALL spInsertProductImage(prodID, 'MAIN', 'https://example.com/img/prod-087.png', 1, TRUE);
    CALL spInsertProduct('PROD-088', site8ID, 'HAIR', 'Rinse de Vinagre de Manzana', 'Rinse capilar de vinagre de manzana', 'SKU-088', usdCurrencyID, 85.3, adminPersonID, prodID);
    CALL spInsertProductPrice(prodID, site8ID, copCurrencyID, 336935.0, CURRENT_TIMESTAMP, NULL, TRUE);
    CALL spInsertProductImage(prodID, 'MAIN', 'https://example.com/img/prod-088.png', 1, TRUE);
    CALL spInsertProduct('PROD-089', site8ID, 'AROMA', 'Aceite Esencial de Cedro', 'Aceite esencial de madera de cedro', 'SKU-089', usdCurrencyID, 86.65, adminPersonID, prodID);
    CALL spInsertProductPrice(prodID, site8ID, copCurrencyID, 342267.5, CURRENT_TIMESTAMP, NULL, TRUE);
    CALL spInsertProductImage(prodID, 'MAIN', 'https://example.com/img/prod-089.png', 1, TRUE);
    CALL spInsertProduct('PROD-090', site9ID, 'SOAP', 'Jabon de Te Verde', 'Jabon antioxidante de te verde', 'SKU-090', usdCurrencyID, 89.5, adminPersonID, prodID);
    CALL spInsertProductPrice(prodID, site9ID, penCurrencyID, 332.94, CURRENT_TIMESTAMP, NULL, TRUE);
    CALL spInsertProductImage(prodID, 'MAIN', 'https://example.com/img/prod-090.png', 1, TRUE);
    CALL spInsertProduct('PROD-091', site9ID, 'ESSOIL', 'Aceite de Marula', 'Aceite premium de marula africana', 'SKU-091', usdCurrencyID, 87.35, adminPersonID, prodID);
    CALL spInsertProductPrice(prodID, site9ID, penCurrencyID, 324.94, CURRENT_TIMESTAMP, NULL, TRUE);
    CALL spInsertProductImage(prodID, 'MAIN', 'https://example.com/img/prod-091.png', 1, TRUE);
    CALL spInsertProduct('PROD-092', site9ID, 'BEVERAGE', 'Infusion de Jengibre y Limon', 'Infusion energizante de jengibre con limon', 'SKU-092', usdCurrencyID, 87.7, adminPersonID, prodID);
    CALL spInsertProductPrice(prodID, site9ID, penCurrencyID, 326.24, CURRENT_TIMESTAMP, NULL, TRUE);
    CALL spInsertProductImage(prodID, 'MAIN', 'https://example.com/img/prod-092.png', 1, TRUE);
    CALL spInsertProduct('PROD-093', site9ID, 'FOOD', 'Pimienta de Jamaica Molida', 'Pimienta gorda molida de la zona sur', 'SKU-093', usdCurrencyID, 89.05, adminPersonID, prodID);
    CALL spInsertProductPrice(prodID, site9ID, penCurrencyID, 331.27, CURRENT_TIMESTAMP, NULL, TRUE);
    CALL spInsertProductImage(prodID, 'MAIN', 'https://example.com/img/prod-093.png', 1, TRUE);
    CALL spInsertProduct('PROD-094', site9ID, 'DERM', 'Aceite Facial de Noche', 'Aceite facial regenerador nocturno', 'SKU-094', usdCurrencyID, 89.4, adminPersonID, prodID);
    CALL spInsertProductPrice(prodID, site9ID, penCurrencyID, 332.57, CURRENT_TIMESTAMP, NULL, TRUE);
    CALL spInsertProductImage(prodID, 'MAIN', 'https://example.com/img/prod-094.png', 1, TRUE);
    CALL spInsertProduct('PROD-095', site9ID, 'HAIR', 'Mascarilla de Platano y Miel', 'Mascarilla capilar de platano con miel', 'SKU-095', usdCurrencyID, 91.25, adminPersonID, prodID);
    CALL spInsertProductPrice(prodID, site9ID, penCurrencyID, 339.45, CURRENT_TIMESTAMP, NULL, TRUE);
    CALL spInsertProductImage(prodID, 'MAIN', 'https://example.com/img/prod-095.png', 1, TRUE);
    CALL spInsertProduct('PROD-096', site9ID, 'AROMA', 'Potpourri de Flores Secas', 'Mezcla de flores secas aromaticas', 'SKU-096', usdCurrencyID, 92.6, adminPersonID, prodID);
    CALL spInsertProductPrice(prodID, site9ID, penCurrencyID, 344.47, CURRENT_TIMESTAMP, NULL, TRUE);
    CALL spInsertProductImage(prodID, 'MAIN', 'https://example.com/img/prod-096.png', 1, TRUE);
    CALL spInsertProduct('PROD-097', site9ID, 'SOAP', 'Jabon de Papaya', 'Jabon aclarante natural de papaya', 'SKU-097', usdCurrencyID, 95.45, adminPersonID, prodID);
    CALL spInsertProductPrice(prodID, site9ID, penCurrencyID, 355.07, CURRENT_TIMESTAMP, NULL, TRUE);
    CALL spInsertProductImage(prodID, 'MAIN', 'https://example.com/img/prod-097.png', 1, TRUE);
    CALL spInsertProduct('PROD-098', site9ID, 'ESSOIL', 'Aceite de Baobab', 'Aceite hidratante de baobab africano', 'SKU-098', usdCurrencyID, 93.3, adminPersonID, prodID);
    CALL spInsertProductPrice(prodID, site9ID, penCurrencyID, 347.08, CURRENT_TIMESTAMP, NULL, TRUE);
    CALL spInsertProductImage(prodID, 'MAIN', 'https://example.com/img/prod-098.png', 1, TRUE);
    CALL spInsertProduct('PROD-099', site9ID, 'BEVERAGE', 'Agua de Coco Natural', 'Agua de coco embotellada sin azucar', 'SKU-099', usdCurrencyID, 93.65, adminPersonID, prodID);
    CALL spInsertProductPrice(prodID, site9ID, penCurrencyID, 348.38, CURRENT_TIMESTAMP, NULL, TRUE);
    CALL spInsertProductImage(prodID, 'MAIN', 'https://example.com/img/prod-099.png', 1, TRUE);
    CALL spInsertProduct('PROD-100', site9ID, 'FOOD', 'Tapa de Dulce Organica', 'Tapa de dulce de cana organica', 'SKU-100', usdCurrencyID, 95.0, adminPersonID, prodID);
    CALL spInsertProductPrice(prodID, site9ID, penCurrencyID, 353.4, CURRENT_TIMESTAMP, NULL, TRUE);
    CALL spInsertProductImage(prodID, 'MAIN', 'https://example.com/img/prod-100.png', 1, TRUE);
    CALL spUpsertInventory(site1ID, (SELECT productID FROM product WHERE productCode = 'PROD-001'), 200, 15, 30, 'HUB');
    CALL spUpsertInventory(site1ID, (SELECT productID FROM product WHERE productCode = 'PROD-002'), 150, 10, 25, 'HUB');
    CALL spUpsertInventory(site1ID, (SELECT productID FROM product WHERE productCode = 'PROD-005'), 180, 8, 20, 'HUB');
    CALL spUpsertInventory(site2ID, (SELECT productID FROM product WHERE productCode = 'PROD-013'), 220, 18, 30, 'HUB');
    CALL spUpsertInventory(site2ID, (SELECT productID FROM product WHERE productCode = 'PROD-017'), 90, 5, 15, 'HUB');
    CALL spUpsertInventory(site3ID, (SELECT productID FROM product WHERE productCode = 'PROD-024'), 170, 12, 25, 'HUB');
    CALL spUpsertInventory(site4ID, (SELECT productID FROM product WHERE productCode = 'PROD-035'), 400, 30, 50, 'HUB');
    CALL spUpsertInventory(site4ID, (SELECT productID FROM product WHERE productCode = 'PROD-040'), 200, 15, 25, 'HUB');
    CALL spUpsertInventory(site5ID, (SELECT productID FROM product WHERE productCode = 'PROD-046'), 300, 20, 35, 'HUB');
    CALL spUpsertInventory(site6ID, (SELECT productID FROM product WHERE productCode = 'PROD-057'), 250, 18, 30, 'HUB');
    CALL spUpsertInventory(site7ID, (SELECT productID FROM product WHERE productCode = 'PROD-068'), 500, 40, 60, 'HUB');
    CALL spUpsertInventory(site7ID, (SELECT productID FROM product WHERE productCode = 'PROD-071'), 250, 20, 30, 'HUB');
    CALL spUpsertInventory(site8ID, (SELECT productID FROM product WHERE productCode = 'PROD-079'), 350, 25, 40, 'HUB');
    CALL spUpsertInventory(site9ID, (SELECT productID FROM product WHERE productCode = 'PROD-090'), 280, 15, 30, 'HUB');
    CALL spUpsertInventory(site9ID, (SELECT productID FROM product WHERE productCode = 'PROD-099'), 320, 22, 35, 'HUB');
    CALL spInsertCustomerOrder('ORD-001', cust1PersonID, site1ID, costaRicaCountryID, crcCurrencyID, 'CREATED', 2500.00, 1.00, 'Primera orden de Laura', order1ID);
    CALL spInsertCustomerOrderDetail(order1ID, (SELECT productID FROM product WHERE productCode = 'PROD-001'), 2, 5283.68, 1374.00, 0.00);
    CALL spInsertCustomerOrderDetail(order1ID, (SELECT productID FROM product WHERE productCode = 'PROD-006'), 1, 6846.32, 890.00, 0.00);
    CALL spInsertPaymentTransaction(order1ID, 'PAY-001', 'VISA', 'APPROVED', 22161.68, crcCurrencyID, 1.00, NULL, 'VISA-REF-001');
    CALL spUpdateCustomerOrderStatus(order1ID, 'PAID', adminPersonID, 'Pago aprobado con Visa');
    CALL spInsertShipment(order1ID, 'SHIP-001', 'PENDING', 'San Jose, Costa Rica', NULL, 'Correos CR', 'CUSTOMER', NULL, NULL);
    CALL spInsertCustomerOrder('ORD-002', cust2PersonID, site2ID, mexicoCountryID, mxnCurrencyID, 'CREATED', 150.00, 1.00, 'Orden de Diego en Mexico', order2ID);
    CALL spInsertCustomerOrderDetail(order2ID, (SELECT productID FROM product WHERE productCode = 'PROD-013'), 1, 318.98, 51.04, 0.00);
    CALL spInsertCustomerOrderDetail(order2ID, (SELECT productID FROM product WHERE productCode = 'PROD-017'), 1, 380.60, 60.90, 0.00);
    CALL spInsertPaymentTransaction(order2ID, 'PAY-002', 'MASTERCARD', 'APPROVED', 961.52, mxnCurrencyID, 1.00, NULL, 'MC-REF-002');
    CALL spUpdateCustomerOrderStatus(order2ID, 'PAID', adminPersonID, 'Pago aprobado con Mastercard');
    CALL spUpdateCustomerOrderStatus(order2ID, 'SHIPPED', adminPersonID, 'Orden enviada');
    CALL spInsertShipment(order2ID, 'SHIP-002', 'IN_TRANSIT', 'Ciudad de Mexico, Mexico', 'TRACK-MX-001', 'FedEx MX', 'CUSTOMER', CURRENT_TIMESTAMP, NULL);
    CALL spInsertCustomerOrder('ORD-003', cust3PersonID, site8ID, colombiaCountryID, copCurrencyID, 'CREATED', 8500.00, 1.00, 'Orden de Valentina', order3ID);
    CALL spInsertCustomerOrderDetail(order3ID, (SELECT productID FROM product WHERE productCode = 'PROD-079'), 3, 233700.00, 91143.00, 0.00);
    CALL spInsertCustomerOrderDetail(order3ID, (SELECT productID FROM product WHERE productCode = 'PROD-085'), 2, 288950.00, 75127.00, 0.00);
    CALL spInsertPaymentTransaction(order3ID, 'PAY-003', 'VISA', 'APPROVED', 697420.00, copCurrencyID, 1.00, NULL, 'VISA-REF-003');
    CALL spUpdateCustomerOrderStatus(order3ID, 'PAID', adminPersonID, 'Pago aprobado');
    CALL spUpdateCustomerOrderStatus(order3ID, 'SHIPPED', adminPersonID, 'Enviado');
    CALL spUpdateCustomerOrderStatus(order3ID, 'DELIVERED', adminPersonID, 'Entregado al cliente');
    CALL spInsertShipment(order3ID, 'SHIP-003', 'DELIVERED', 'Bogota, Colombia', 'TRACK-CO-001', 'Servientrega', 'CUSTOMER', DATE_SUB(CURRENT_TIMESTAMP, INTERVAL 3 DAY), CURRENT_TIMESTAMP);
    CALL spInsertCustomerOrder('ORD-004', cust4PersonID, site4ID, peruCountryID, penCurrencyID, 'CREATED', 10.00, 1.00, 'Orden de Miguel en Peru', order4ID);
    CALL spInsertCustomerOrderDetail(order4ID, (SELECT productID FROM product WHERE productCode = 'PROD-035'), 2, 142.41, 37.03, 0.00);
    CALL spInsertCustomerOrderDetail(order4ID, (SELECT productID FROM product WHERE productCode = 'PROD-040'), 1, 168.07, 43.70, 0.00);
    CALL spInsertPaymentTransaction(order4ID, 'PAY-004', 'VISA', 'APPROVED', 533.62, penCurrencyID, 1.00, NULL, 'VISA-REF-004');
    CALL spUpdateCustomerOrderStatus(order4ID, 'PAID', adminPersonID, 'Pago aprobado');
    CALL spInsertShipment(order4ID, 'SHIP-004', 'PENDING', 'Lima, Peru', NULL, 'Olva Courier', 'CUSTOMER', NULL, NULL);
    CALL spInsertCustomerOrder('ORD-005', cust5PersonID, site5ID, guatemalaCountryID, gtqCurrencyID, 'CREATED', 25.00, 1.00, 'Orden de Sofia en Guatemala', order5ID);
    CALL spInsertCustomerOrderDetail(order5ID, (SELECT productID FROM product WHERE productCode = 'PROD-046'), 1, 325.26, 42.28, 0.00);
    CALL spInsertCustomerOrderDetail(order5ID, (SELECT productID FROM product WHERE productCode = 'PROD-051'), 2, 362.70, 94.30, 0.00);
    CALL spInsertPaymentTransaction(order5ID, 'PAY-005', 'VISA', 'APPROVED', 1186.84, gtqCurrencyID, 1.00, NULL, 'VISA-REF-005');
    CALL spUpdateCustomerOrderStatus(order5ID, 'PAID', adminPersonID, 'Pago aprobado');
    CALL spInsertShipment(order5ID, 'SHIP-005', 'PENDING', 'Ciudad de Guatemala, Guatemala', NULL, 'Cargo Expreso', 'CUSTOMER', NULL, NULL);
    CALL spInsertCountryProductPermission(
        (SELECT productID FROM product WHERE productCode = 'PROD-001'), costaRicaCountryID, 50000,
        'PERM-CR-001', 'Registro sanitario bebida organica', 'APPROVED', 'CERT-CR-001',
        'Ministerio de Salud CR', CURRENT_TIMESTAMP, DATE_ADD(CURRENT_TIMESTAMP, INTERVAL 1 YEAR), 'Permiso aprobado');
    CALL spInsertCountryProductPermission(
        (SELECT productID FROM product WHERE productCode = 'PROD-035'), peruCountryID, 30000,
        'PERM-PE-001', 'Registro sanitario aceite esencial', 'APPROVED', 'CERT-PE-001',
        'DIGESA Peru', CURRENT_TIMESTAMP, DATE_ADD(CURRENT_TIMESTAMP, INTERVAL 2 YEAR), 'Producto aprobado');
    CALL spInsertCountryProductPermission(
        (SELECT productID FROM product WHERE productCode = 'PROD-046'), guatemalaCountryID, 25000,
        'PERM-GT-001', 'Licencia cosmetico capilar', 'APPROVED', 'CERT-GT-001',
        'MAGA Guatemala', CURRENT_TIMESTAMP, DATE_ADD(CURRENT_TIMESTAMP, INTERVAL 1 YEAR), 'Exportacion aprobada');
    CALL spInsertCountryProductPermission(
        (SELECT productID FROM product WHERE productCode = 'PROD-068'), mexicoCountryID, 40000,
        'PERM-MX-001', 'Registro sanitario aromaterapia', 'PENDING', NULL,
        'COFEPRIS Mexico', CURRENT_TIMESTAMP, NULL, 'En proceso de aprobacion');
    CALL spInsertCountryProductPermission(
        (SELECT productID FROM product WHERE productCode = 'PROD-079'), colombiaCountryID, 35000,
        'PERM-CO-001', 'Registro INVIMA alimento organico', 'APPROVED', 'CERT-CO-001',
        'INVIMA Colombia', CURRENT_TIMESTAMP, DATE_ADD(CURRENT_TIMESTAMP, INTERVAL 2 YEAR), 'Aprobado por INVIMA');
    CALL spInsertCountryProductRequirement(
        (SELECT productID FROM product WHERE productCode = 'PROD-001'), costaRicaCountryID,
        'HEALTH', 'Registro sanitario obligatorio', 'Todo producto de consumo requiere registro sanitario',
        TRUE, 'Ministerio de Salud CR', CURRENT_TIMESTAMP, DATE_ADD(CURRENT_TIMESTAMP, INTERVAL 2 YEAR));
    CALL spInsertCountryProductRequirement(
        (SELECT productID FROM product WHERE productCode = 'PROD-035'), peruCountryID,
        'LABELING', 'Etiquetado de aceites esenciales', 'Debe incluir composicion y advertencias en espanol',
        TRUE, 'DIGESA Peru', CURRENT_TIMESTAMP, NULL);
    CALL spInsertCountryProductRequirement(
        (SELECT productID FROM product WHERE productCode = 'PROD-046'), guatemalaCountryID,
        'IMPORT', 'Certificado de origen', 'Certificado de origen para cosmeticos capilares',
        TRUE, 'MAGA Guatemala', CURRENT_TIMESTAMP, DATE_ADD(CURRENT_TIMESTAMP, INTERVAL 1 YEAR));
    COMMIT;
    CALL spLogEtlStep('spSeedFullData', 'MANUAL', 'dynamicBrandsDB', 'SUCCESS', 0, 0, NULL);
END $$
DELIMITER ;
CALL spSeedFullData();
